[192] Generalise public discourse analysis
nestauk/innovation_sweet_spots pull request #195
Opened 2022-10-28 02:45 UTC by Jack-0-0

Closes #192.

---

Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [ ] I have checked the code runs
- [ ] I have tested the code
- [ ] I have run `pre-commit` and addressed any issues not automatically fixed
- [ ] I have merged any new changes from `dev`
- [ ] I have documented the code
  - [ ] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [ ] I have explained the feature in this PR or (better) in `output/reports/`
- [ ] I have requested a code review

2022-11-10 18:12 UTC, beingkk commented on innovation_sweet_spots/utils/pd/pd_analysis_utils.py
> +            self._list_of_pos_phrases = self.pos_phrases.phrase.to_list()
Shouldn't the phrases be deduplicated first?

2022-11-10 18:23 UTC, beingkk commented
Thank you very much @Jack-0-0 for this, it's really great! I've tested the code by running the Colab notebook (which worked very well for me).

### `plot_mentions` function
An issue I noticed with the `plot_mentions(use_documents=False)` function, when plotting number of sentences, was that it only uses the first column. Perhaps a quick fix can be to use a stacked bar chart and show all columns?

![Screenshot 2022-11-10 at 17 48 04](https://user-images.githubusercontent.com/29844253/201169349-13dc6046-d4a7-4431-9437-e3ae2bb02c66.png)

### Adding an extra pattern
This is not a bug, but I wondered if we could add another pattern to the list of automatically generated patterns - I would like to see a variation of noun phrase where the search terms is in the front.

So, for example, at the moment, if I search for 'obesity' I'll have things like "adult obesity" and "childhood obesity".

However, I would also like to find things like "obesity crisis" or "obesity pandemic"

I think this could be relatively easily done by swapping a few lines for the very first pattern? eg, perhaps something like...
```
[ {'TEXT': 'obesity'},
  {'POS': 'NOUN'},
  {'POS': 'NOUN', 'OP': '?'},
]
```

You can also imagine examples with "food" like "food preparation", "food insecurity", "food poverty" etc.

### BERTopic visualisation: hover data
I realise this comes "out of the box" and perhaps we can't change anything, but maybe it's possible to:
- Add year to the hover-over data
- Break long sentences into multiple lines
However, it might be the case that it's not possible without changing BERTopic library itself (which we don't want to do here).

### BERTopic visualisation: topics
I'm a bit confused about why there are different number of topics in the first and second graph... does it just limit the bar chart graph to 8? It's also a bit annoying that the colours don't match between both, but that's a very minor issue.

![Screenshot 2022-11-10 at 18 02 53](https://user-images.githubusercontent.com/29844253/201172231-e874c4d8-8afc-4a88-a3e4-28c12716bea4.png)

![Screenshot 2022-11-10 at 18 03 08](https://user-images.githubusercontent.com/29844253/201172278-4f8c2aad-14ba-4083-99bd-c90b9a991eb7.png)

2022-11-10 18:25 UTC, beingkk requested changes
Thanks so much again, I'm really happy about this PR - please see just a few small things I've commented above.

Once you make the changes, please don't merge it yet into dev, as I'm still working on finalising the public discourse analysis using the old utils. Once I'm done with my analysis, I will merge it and check that my code is not broken.

2022-11-12 12:41 UTC, Jack-0-0 commented
> ### `plot_mentions` function
> An issue I noticed with the `plot_mentions(use_documents=False)` function, when plotting number of sentences, was that it only uses the first column. Perhaps a quick fix can be to use a stacked bar chart and show all columns?
> 
I have updated `plot_mentions` to use a stacked bar chart now. If you run `plot_mentions(use_documents=False)`, it will produce a stacked bar chart.

![Screenshot 2022-11-12 at 21 40 16](https://user-images.githubusercontent.com/47244945/201474367-16df1d92-bdda-4cc0-9880-cd0959e7ad53.png)


If you run `plot_mentions(use_documents=True)`, it will produce a regular bar chart as `document_mentions` only shows total mentions, it does not separate the mentions by different search terms.

2022-11-12 14:34 UTC, Jack-0-0 commented
> ### BERTopic visualisation: topics
> I'm a bit confused about why there are different number of topics in the first and second graph... does it just limit the bar chart graph to 8? It's also a bit annoying that the colours don't match between both, but that's a very minor issue.
> 

`visualize_barchart` has a parameter `top_n_topics` which defaults to 8. I have set the notebook cell to now use `visualize_barchart(top_n_topics=len(set(topic_model.topics_)))` so that it shows all the topics.

I couldn't see any options in BERTopic to change the colour palette.

2022-11-12 14:38 UTC, Jack-0-0 commented
> ### BERTopic visualisation: hover data
> I realise this comes "out of the box" and perhaps we can't change anything, but maybe it's possible to:
> 
> * Add year to the hover-over data
> * Break long sentences into multiple lines
>   However, it might be the case that it's not possible without changing BERTopic library itself (which we don't want to do here).
> 

I couldn't see these options in BERTopic.

However, you can adjust the size of the plot with the parameters `width` and `height`. When the plot is larger it allows for longer sentences to be displayed. I have increased the size of the plot in the demo notebook and added a note relating to these parameters for users.

2022-11-12 15:08 UTC, Jack-0-0 commented
> ### Adding an extra pattern
> This is not a bug, but I wondered if we could add another pattern to the list of automatically generated patterns - I would like to see a variation of noun phrase where the search terms is in the front.
> 
> So, for example, at the moment, if I search for 'obesity' I'll have things like "adult obesity" and "childhood obesity".
> 
> However, I would also like to find things like "obesity crisis" or "obesity pandemic"
> 
> I think this could be relatively easily done by swapping a few lines for the very first pattern? eg, perhaps something like...
> 
> ```
> [ {'TEXT': 'obesity'},
>   {'POS': 'NOUN'},
>   {'POS': 'NOUN', 'OP': '?'},
> ]
> ```
> 
> You can also imagine examples with "food" like "food preparation", "food insecurity", "food poverty" etc.
> 

I have added the pattern as suggested.
It is named `f"{term_dict_lbl}_term_noun"` in the phrase patterns dictionary.

2022-11-12 15:09 UTC, Jack-0-0 commented
Thanks for the review @beingkk. I have made changes relating to your comments.
Let me know when you're happy for me to merge 🙂

2022-11-23 15:29 UTC, beingkk approved these changes
Thanks so much Jack, looks good to merge!

2022-11-29 05:12 UTC, merged