[204] Optimal clustering parameters
nestauk/innovation_sweet_spots pull request #206
Opened 2022-11-30 02:26 UTC by Jack-0-0

---

Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [ ] I have checked the code runs
- [ ] I have tested the code
- [ ] I have run `pre-commit` and addressed any issues not automatically fixed
- [ ] I have merged any new changes from `dev`
- [ ] I have documented the code
  - [ ] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [ ] I have explained the feature in this PR or (better) in `output/reports/`
- [ ] I have requested a code review

2022-11-30 09:21 UTC, beingkk commented on innovation_sweet_spots/utils/cluster_analysis_utils.py
> +            silhouette = silhouette_score(reduced_dims_vectors, clusters)
Perhaps we can use a pre-computed distance matrix here instead of `reduced_dims_vectors` to speed up the grid search (for `silhouette_score` )

2022-12-01 08:41 UTC, Jack-0-0 commented on innovation_sweet_spots/utils/cluster_analysis_utils.py
> +            silhouette = silhouette_score(reduced_dims_vectors, clusters)
I also noticed that the umap reducer was being run on each parameter search iteration.
I ran some experiments using precomputed distances and running the reducer only once.
For HDBSCAN it reduces each iteration from ~22 secs down to ~4 secs.
For K-Means it reduces each iteration from ~20 secs down to ~2 secs

2022-12-12 15:36 UTC, beingkk requested changes
Hey @Jack-0-0 thanks so much - it looks very good to me! I've added a few lines that also allows to visualise a clustering result using the best parameters (so, you should `git pull` to see these changes)

I only have two requests, which I hope are not too tricky to implement - do let me know if you think the time is too short:

- Given that the clustering is rather quick, could you please add an option to run each parameter set `n` times using different random seeds, where `n` can be chosen by the user (eg, default could be `n=1` but the user could also set it to higher in which case the function could return mean and standard deviation of the silhouette score). In that way, we'll have increased confidence that the silhouette score for the optimal parameter set is robust

- For the hdbscan clustering results, could you please adjust the `hdbscan_clustering` function so that it doesn't use the "-1" cluster (which are the points that are considered noisy). I think this will otherwise have an impact on the silhouette score. I’ve made a corresponding comment in the code - we can also discuss during tomorrow’s catchup.

2022-12-12 15:36 UTC, beingkk commented on innovation_sweet_spots/utils/cluster_analysis_utils.py
> +    highest_cluster_prob = np.array([(np.argmax(x), np.max(x)) for x in cluster_probs])
Could we adjust this line so that the user can choose whether to use the "-1" (noise) cluster label, or rather instead ignore it and assign the points to the next best cluster? Otherwise, I think it assigns a lot of points to the noise cluster, which probably will impact the silhouette score...

2022-12-12 15:36 UTC, beingkk commented on innovation_sweet_spots/utils/cluster_analysis_utils.py
> +    highest_cluster_prob = np.array([(np.argmax(x), np.max(x)) for x in cluster_probs])
I think by default we should ignore the noise cluster

2022-12-15 13:53 UTC, Jack-0-0 commented
It seems that HDBSCAN is deterministic. I have therefore split the `param_grid_search` function into two functions, `kmeans_param_grid_search` and `hdbscan_param_grid_search`.

`kmeans_param_grid_search` has an additional parameter `random_seeds` which is a list of random seeds. The function will do paramer search for each seed in `random_seeds` and then take the mean of all the random seed runs.

I have removed the random seed parameter for `hdbscan_clustering`.

2022-12-16 04:21 UTC, Jack-0-0 commented
Regarding not using the noise labels, the way the function was originally implemented, it wasn't using the noise labels but was assigning a label that corresponds to the index of the largest value in `hdbscan.all_points_membership_vectors` output (of which none relate to noise).

However, I noticed that in some cases the probabilities in `hdbscan.all_points_membership_vectors` for some vectors are all 0s. So in that case, I have changed it so the vector will be assigned a `-2` label.

I have added a way to have some of the points be labelled as noise using `labels_` built into HDBSCAN.

Interestingly, when allowing points to be assigned to noise, the average silhouette scores go negative.

2022-12-16 18:14 UTC, beingkk commented
Thank you!

2022-12-16 18:15 UTC, merged